<?php
$scoreService=new ScorebookService(database_pdo());$scoreError='';$scoreRows=array();$allocation=null;$config=array();
$allocations=$scoreService->allocations($_SESSION['active']);
$class=$portalRoute->param('class_id','');$subject=$portalRoute->param('subject_id','');$week=(int)$portalRoute->param('instance',0);
try { $config=$scoreService->config();if($class && $subject) { $allocation=$scoreService->allocation($_SESSION['active'],$class,$subject);$scoreRows=$scoreService->sheet($_SESSION['active'],$class,$subject,$week); } } catch(Throwable $e) { $scoreError=$e instanceof PDOException?'Unable to load this scorebook.':$e->getMessage(); }
$locked=empty($config) || (int)$config[$week?'midterm':'status']===1;
$h=function($v){return htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');};
?>
<div class="main_content_iner school-workspace"><div class="container-fluid p-0"><header class="workspace-heading"><div><p class="workspace-eyebrow">Teaching · <?php echo $h($scoreService->activeTerm()); ?></p><h1>Class scorebook</h1><p>A practical place to record, check and save your learners’ scores.</p></div><button class="workspace-button secondary no-print" data-print type="button">Print scorebook</button></header>
<?php if($scoreError): ?><div class="workspace-error" role="alert"><?php echo $h($scoreError); ?></div><?php endif; ?>
<section class="workspace-card no-print"><form method="get" action="../../app/router.php" class="workspace-toolbar" id="score-selector"><input type="hidden" name="pageid" value="scoresheet"><input type="hidden" name="class_id" id="score-class" value="<?php echo $h($class); ?>">
<label>Class and subject<select name="subject_id" id="score-subject" required><option value="">Choose an allocated subject</option><?php foreach($allocations as $a): ?><option data-class="<?php echo (int)$a['classid']; ?>" value="<?php echo (int)$a['sbjid']; ?>" <?php echo (string)$a['classid']===$class && (string)$a['sbjid']===$subject?'selected':''; ?>><?php echo $h($a['classname'].' · '.$a['sbjname']); ?></option><?php endforeach; ?></select></label>
<label>Assessment period<select name="instance"><option value="0">Term · CA &amp; examination</option><?php for($w=1;$w<=13;$w++): ?><option value="<?php echo $w; ?>" <?php echo $week===$w?'selected':''; ?>>Week <?php echo $w; ?> · out of 10</option><?php endfor; ?></select></label><button class="workspace-button">Open scorebook</button></form><small>Blank fields keep the current score. Enter 0 for a genuine zero. Scores use whole marks, matching your existing result records.</small></section>
<?php if($allocation && !$scoreError): ?><section class="workspace-card"><div class="workspace-heading"><div><h2><?php echo $h($allocation['classname'].' · '.$allocation['sbjname']); ?></h2><p><?php echo $week?'Week '.$week:'Term scores'; ?> · <?php echo count($scoreRows); ?> learners</p></div><span class="workspace-badge <?php echo $locked?'warning':''; ?>"><?php echo $locked?'Entry locked by administrator':'Open for entry'; ?></span></div>
<label class="no-print">Find a learner<input type="search" data-table-search="#score-table" placeholder="Name or learner ID"></label>
<form id="scorebook" action="../../app/scores.php" method="post"><input type="hidden" name="csrf_token" value="<?php echo $h($_SESSION['portal_csrf']); ?>"><input type="hidden" name="class_id" value="<?php echo $h($class); ?>"><input type="hidden" name="subject_id" value="<?php echo $h($subject); ?>"><input type="hidden" name="week" value="<?php echo $week; ?>">
<div class="workspace-table-wrap score-table-wrap"><table class="workspace-table score-table" id="score-table"><thead><tr><th>Learner</th><th><?php echo $week?'Weekly / 10':'CA / '.(int)$config['ca_score']; ?></th><?php if(!$week): ?><th>Exam / <?php echo (int)$config['exam_score']; ?></th><th>Total</th><?php endif; ?><th>Record</th></tr></thead><tbody>
<?php foreach($scoreRows as $row): ?><tr data-learner="<?php echo $h($row['uname']); ?>" data-version="<?php echo $h($row['version']); ?>"><td><strong><?php echo $h($row['fname']); ?></strong><small><?php echo $h($row['uname']); ?></small></td>
<?php foreach($week?array('score'=>10):array('score'=>(int)$config['ca_score'],'examscore'=>(int)$config['exam_score']) as $col=>$max): ?><td><input type="number" data-column="<?php echo $col; ?>" data-initial="<?php echo $h($row['record'][$col] ?? ''); ?>" value="<?php echo $h($row['record'][$col] ?? ''); ?>" min="0" max="<?php echo $max; ?>" step="1" aria-label="<?php echo $h(($col==='examscore'?'Exam':'Assessment').' score for '.$row['fname']); ?>" <?php echo $locked?'disabled':''; ?>></td><?php endforeach; ?>
<?php if(!$week): ?><td><output><?php echo $row['record']?(int)$row['record']['totalscore']:'—'; ?></output></td><?php endif; ?><td data-row-status><?php echo $row['record']?'Recorded':'Not recorded'; ?></td></tr><?php endforeach; ?></tbody></table></div>
<div class="score-footer no-print"><span id="score-status" role="status" aria-live="polite">No unsaved changes</span><button class="workspace-button" id="score-save" <?php echo $locked?'disabled':''; ?>>Save changes</button></div></form><?php if(!$scoreRows): ?><p class="workspace-empty">No active learners in this class.</p><?php endif; ?></section>
<?php elseif(!$scoreError): ?><section class="workspace-card workspace-empty"><h2>Choose your class to get started</h2><p>Your current subject allocations are available above.</p></section><?php endif; ?></div></div>
<script src="../../../assets/js/scorebook.js?v=2" defer></script>
