<?php

return array(
    'dashboard' => 'dashboard.php',
    'profile' => 'profile.php',
    'staff' => 'mgstaff.php',
    'learners' => 'mglearners.php',
    'terms' => 'mgterm.php',
    'calendar' => 'calendar.php',
    'result-config' => 'mgconfig.php',
    'records' => 'mgresult.php',
    'affective' => 'mgaffective.php',
    'midterm' => 'mgmid.php',
    'reports' => 'mgreport.php',
    'report-view' => 'viewresult.php',
    'report-cumulative' => 'viewcumresult.php',
    'reports-class' => 'viewmultiresult.php',
    'reports-class-cumulative' => 'viewmulticum.php',
    'promotions' => 'promote.php',
    'fees' => 'mgfee.php',
    'fee-assignments' => 'assignfee.php',
    'discounts' => 'mgdiscount.php',
    'expenses' => 'expenses.php',
    'inventory' => 'inventory.php',
    'payments' => 'payrecord.php',
    'payment-reports' => 'payreport.php',
    'payment-view' => 'payview.php',
    'classes' => 'cclass.php',
    'subjects' => 'csubj.php',
    'allocations' => 'allocate.php',
    'resources' => 'mglesson.php',
    'resource-dashboard' => 'filedash.php',
    'cbt' => 'cbt.php',
);
