<?php
require __DIR__ . '/workflow_bootstrap.php';
$service=new FeeService($workflowDb);
$term=is_string($_GET['term'] ?? null)?$_GET['term']:$service->activeTerm();
$classFilter=(int)($_GET['class_id'] ?? 0);$status=is_string($_GET['status'] ?? null)?$_GET['status']:'active';
if($_SERVER['REQUEST_METHOD']==='POST'){
    try{
        CbtSecurity::requireCsrf($_POST['csrf_token'] ?? '','admin');$action=$_POST['action'] ?? 'assign';
        if(!in_array($action,array('assign','status'),true))throw new InvalidArgumentException('Unknown fee assignment action.');
        if($action==='status'){
            $targetStatus=(int)($_POST['status'] ?? -1);$service->changeAssignmentStatus($_POST['id'] ?? 0,$targetStatus,$_SESSION['unamed'],($_POST['confirm'] ?? '')==='yes');
            workflow_redirect('fee-assignments',$targetStatus?'Assigned fee activated.':'Assigned fee deactivated. The record and payment history remain available.');
        }
        $result=$service->assign($_POST,$_SESSION['unamed']);
        workflow_redirect('fee-assignments',number_format($result['created']).' learner charge'.($result['created']===1?' was':'s were').' created; '.number_format($result['skipped']).' existing active assignment'.($result['skipped']===1?' was':'s were').' skipped.');
    }catch(Throwable $e){$workflowError=workflow_error($e);}
}
$terms=array();$classes=array();$fees=array();$assignments=array();$learners=array();$summary=array('active_records'=>0,'inactive_records'=>0,'active_payable'=>0);
try{
    $terms=$service->terms();$classes=$service->classes();$fees=$service->definitionsForTerm($term,'active');$summary=$service->assignmentSummary($term);$assignments=$service->assignments($term,$classFilter,$status);
    $selectedClass=(int)($_POST['class_id'] ?? 0);if($selectedClass)$learners=$service->learners($selectedClass);
}catch(Throwable $e){$workflowError=workflow_error($e);}
$form=$workflowError && $_SERVER['REQUEST_METHOD']==='POST'?$_POST:array();
$workflowTitle='Assign fees';$workflowIntro='Choose a term, then apply a reusable session fee to one learner, a class, or the school.';$workflowScripts=array('../assets/js/fees.js?v=2');
require __DIR__ . '/workflow_header.php';
?>
<nav class="workspace-subnav no-print" aria-label="Fee management"><a href="index.php?route=fees">Fee setup</a><a class="active" href="index.php?route=fee-assignments">Assign fees</a><a href="index.php?route=discounts">Discounts</a><a href="index.php?route=payments">Payments</a></nav>
<div class="workspace-stats"><div><span>Active assigned fees</span><strong><?php echo number_format((int)$summary['active_records']); ?></strong></div><div><span>Current payable before payments</span><strong>₦<?php echo number_format((int)$summary['active_payable']); ?></strong></div><div><span>Inactive records · retained</span><strong><?php echo number_format((int)$summary['inactive_records']); ?></strong></div></div>
<div class="workspace-grid fee-workspace"><section class="workspace-card"><p class="workspace-eyebrow">Term-specific learner charge</p><h2>Assign a session fee</h2><p class="workspace-muted">The selected catalogue fee is saved against <?php echo wh($term); ?>. Existing active copies in this term are skipped automatically.</p>
<?php if($fees): ?><form method="post" data-fee-assignment data-learners-url="fee_learners.php"><input type="hidden" name="action" value="assign"><input type="hidden" name="csrf_token" value="<?php echo wh($workflowCsrf); ?>">
<div class="workspace-fields"><label class="workspace-wide">Academic term<select name="term" data-fee-term required><?php foreach($terms as $row): ?><option value="<?php echo wh($row['term']); ?>" <?php echo $term===$row['term']?'selected':''; ?>><?php echo wh($row['term'].((int)$row['status']===1?' · Active':'')); ?></option><?php endforeach; ?></select><small>Changing the term reloads the fee catalogue for that academic session.</small></label><label class="workspace-wide">Who should receive the fee?<select name="audience" data-fee-audience required><option value="learner" <?php echo ($form['audience'] ?? '')==='learner'?'selected':''; ?>>One learner</option><option value="class" <?php echo ($form['audience'] ?? '')==='class'?'selected':''; ?>>Every active learner in one class</option><option value="school" <?php echo ($form['audience'] ?? '')==='school'?'selected':''; ?>>Every active learner in the school</option></select></label>
<label class="workspace-wide" data-assignment-class>Class<select name="class_id" data-assignment-class-select><option value="">Choose class</option><?php foreach($classes as $row): ?><option value="<?php echo (int)$row['classid']; ?>" <?php echo (string)($form['class_id'] ?? '')===(string)$row['classid']?'selected':''; ?>><?php echo wh($row['classname']); ?></option><?php endforeach; ?></select></label>
<label class="workspace-wide" data-assignment-learner>Learner<select name="learner_id" data-assignment-learner-select data-current="<?php echo wh($form['learner_id'] ?? ''); ?>"><option value="">Choose class first</option><?php foreach($learners as $row): ?><option value="<?php echo wh($row['uname']); ?>" <?php echo ($form['learner_id'] ?? '')===$row['uname']?'selected':''; ?>><?php echo wh($row['learner_name'].' · '.$row['uname']); ?></option><?php endforeach; ?></select><small data-learner-help>Only active learners in the selected class are shown.</small></label>
<label class="workspace-wide">Fee<select name="fee_id" data-assignment-fee required><option value="">Choose fee</option><option value="PreviousBalance" data-group="school" data-amount="">Previous term balance · enter amount</option><?php foreach($fees as $row): ?><option value="<?php echo (int)$row['feeid']; ?>" data-group="<?php echo ctype_digit((string)$row['classid'])?'class':'school'; ?>" data-class="<?php echo ctype_digit((string)$row['classid'])?(int)$row['classid']:''; ?>" data-amount="<?php echo (int)$row['amount']; ?>" <?php echo (string)($form['fee_id'] ?? '')===(string)$row['feeid']?'selected':''; ?>><?php echo wh($row['feename'].' · '.($row['classname'] ?: $row['classid']).' · ₦'.number_format((int)$row['amount'])); ?></option><?php endforeach; ?></select><small data-fee-preview>Select a fee to review its amount and availability.</small></label>
<label class="workspace-wide" data-custom-amount>Outstanding balance (₦)<input type="number" name="custom_amount" min="1" max="1000000000" step="1" value="<?php echo wh($form['custom_amount'] ?? ''); ?>"></label><label class="workspace-wide">Payment due date<input type="date" name="due" required value="<?php echo wh($form['due'] ?? date('Y-m-d',strtotime('+30 days'))); ?>"></label></div><button class="workspace-button">Assign fee</button></form>
<?php else: ?><div class="workspace-empty"><h3>Create a fee first</h3><p>No active fee definitions were found in the academic session for <?php echo wh($term); ?>.</p><a class="workspace-button" href="index.php?route=fees">Create reusable fee</a></div><?php endif; ?></section>
<section class="workspace-card"><h2>Before you assign</h2><ol class="fee-checklist"><li>Choose the exact term and approved fee.</li><li>Select one learner, a class, or the whole school.</li><li>Review the amount and due date.</li><li>Submit once; active duplicates are skipped safely.</li></ol><div class="fee-callout"><strong>Previous balance</strong><p>Use it only for a verified brought-forward amount. The custom amount is applied to every recipient in the selected audience.</p></div></section></div>
<section class="workspace-card"><div class="fee-section-heading"><div><h2>Assigned-fee register</h2><p class="workspace-muted">Latest 250 matching records for <?php echo wh($term); ?></p></div><button type="button" class="workspace-button secondary no-print" data-print>Print register</button></div>
<form method="get" class="workspace-toolbar"><input type="hidden" name="route" value="fee-assignments"><label>Academic term<select name="term"><?php foreach($terms as $row): ?><option value="<?php echo wh($row['term']); ?>" <?php echo $term===$row['term']?'selected':''; ?>><?php echo wh($row['term']); ?></option><?php endforeach; ?></select></label><label>Class<select name="class_id"><option value="0">All classes</option><?php foreach($classes as $row): ?><option value="<?php echo (int)$row['classid']; ?>" <?php echo $classFilter===(int)$row['classid']?'selected':''; ?>><?php echo wh($row['classname']); ?></option><?php endforeach; ?></select></label><label>Status<select name="status"><option value="active" <?php echo $status==='active'?'selected':''; ?>>Active</option><option value="inactive" <?php echo $status==='inactive'?'selected':''; ?>>Inactive</option><option value="all" <?php echo $status==='all'?'selected':''; ?>>All</option></select></label><button class="workspace-button secondary">Apply filters</button></form><label class="no-print">Find a learner or fee<input type="search" data-table-search="#assigned-fee-table" placeholder="Learner, class, fee or term"></label>
<div class="workspace-table-wrap"><table class="workspace-table" id="assigned-fee-table"><thead><tr><th>Learner / class</th><th>Fee</th><th>Due</th><th>Amount</th><th>Discount</th><th>Payable</th><th>Status</th><th class="no-print"></th></tr></thead><tbody><?php foreach($assignments as $row): ?><tr><td><strong><?php echo wh($row['learner_name']); ?></strong><small><?php echo wh($row['class_name'].' · '.$row['stdid']); ?></small></td><td><?php echo wh($row['fee_name']); ?><small><?php echo wh($row['type']); ?></small></td><td><?php echo wh($row['due']); ?></td><td class="money">₦<?php echo number_format((int)$row['amount']); ?></td><td class="money">₦<?php echo number_format((int)$row['discount']); ?></td><td class="money"><strong>₦<?php echo number_format((int)$row['amount']-(int)$row['discount']); ?></strong></td><td><span class="workspace-badge <?php echo (int)$row['status']===1?'':'muted'; ?>"><?php echo (int)$row['status']===1?'Active':'Inactive'; ?></span></td><td class="no-print"><form method="post" <?php if((int)$row['status']===1): ?>data-confirm="Deactivate this learner fee? The record and payment history will remain available."<?php endif; ?>><input type="hidden" name="action" value="status"><input type="hidden" name="csrf_token" value="<?php echo wh($workflowCsrf); ?>"><input type="hidden" name="id" value="<?php echo (int)$row['assid']; ?>"><input type="hidden" name="status" value="<?php echo (int)$row['status']===1?0:1; ?>"><?php if((int)$row['status']===1): ?><input type="hidden" name="confirm" value="yes"><button class="workspace-button danger compact">Deactivate</button><?php else: ?><button class="workspace-button secondary compact">Activate</button><?php endif; ?></form></td></tr><?php endforeach; ?></tbody></table></div><?php if(!$assignments): ?><div class="workspace-empty"><h3>No assigned fees match these filters</h3><p>Change the term, class or status, or assign a fee above.</p></div><?php endif; ?></section>
<?php require __DIR__ . '/workflow_footer.php'; ?>
