<?php
require __DIR__ . '/workflow_bootstrap.php';
$service = new InventoryService($workflowDb);
if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    try {
        CbtSecurity::requireCsrf($_POST['csrf_token'] ?? '', 'admin');
        if (!in_array($_POST['action'] ?? '',array('save','move','archive'),true)) throw new InvalidArgumentException('Unknown inventory action.');
        if (($_POST['action'] ?? '') === 'move') { $service->move($_POST,$_SESSION['unamed']); workflow_redirect('inventory','Stock movement recorded.',(int)$_POST['id']); }
        if (($_POST['action'] ?? '') === 'archive') { $service->archive($_POST['id'] ?? 0,$_SESSION['unamed'],($_POST['confirm'] ?? '') === 'yes'); workflow_redirect('inventory','Item archived. Its movement history is retained.'); }
        $id = $service->save($_POST,$_SESSION['unamed']); workflow_redirect('inventory','Item saved. Use Receive stock to record quantities.',$id);
    } catch (Throwable $e) { $workflowError = workflow_error($e); }
}
$edit = null; $history = array();
try { if (!empty($_GET['id'])) { $edit=$service->get($_GET['id']); $history=$edit ? $service->history($edit['id']) : array(); } } catch(Throwable $e) { $workflowError=workflow_error($e); }
$form = $workflowError && ($_POST['action'] ?? '') === 'save' ? $_POST : ($edit ?: array());
$items=$service->items(); $active=array_filter($items,function($i){return $i['active'];}); $low=array_filter($active,function($i){return $i['quantity']<=$i['minimum_stock'];});
$value=0;foreach($active as $i) $value += $i['quantity']*$i['unit_cost'];
$workflowTitle='Inventory';$workflowIntro='Know what is available, where it is kept, and who received it. Every stock movement leaves a trace.';
require __DIR__ . '/workflow_header.php';
?>
<div class="workspace-stats"><div><span>Active items</span><strong><?php echo count($active); ?></strong></div><div><span>At or below reorder level</span><strong><?php echo count($low); ?></strong></div><div><span>Estimated stock value · current unit costs</span><strong>₦<?php echo number_format($value,2); ?></strong></div></div>
<div class="workspace-grid"><div><section class="workspace-card"><h2><?php echo $edit ? wh($edit['name']) : 'Add an inventory item'; ?></h2>
<form method="post"><input type="hidden" name="action" value="save"><input type="hidden" name="csrf_token" value="<?php echo wh($workflowCsrf); ?>"><input type="hidden" name="id" value="<?php echo (int)($edit['id'] ?? 0); ?>"><input type="hidden" name="version" value="<?php echo (int)($form['version'] ?? 0); ?>"><div class="workspace-fields">
<?php foreach(array('sku'=>array('Item code',60),'name'=>array('Item name',160),'category'=>array('Category',80),'unit'=>array('Unit (e.g. pieces)',30),'location'=>array('Storage location',120)) as $field=>$meta): ?><label <?php echo $field==='name'?'class="workspace-wide"':''; ?>><?php echo wh($meta[0]); ?><input name="<?php echo $field; ?>" required maxlength="<?php echo $meta[1]; ?>" value="<?php echo wh($form[$field] ?? ''); ?>"></label><?php endforeach; ?>
<label>Reorder level<input type="number" name="minimum_stock" min="0" step="1" required value="<?php echo (int)($form['minimum_stock'] ?? 0); ?>"></label><label>Unit cost (₦)<input type="number" name="unit_cost" min="0" step="0.01" required value="<?php echo wh($form['unit_cost'] ?? '0.00'); ?>"></label></div><div class="workspace-actions"><button class="workspace-button">Save item</button><?php if($edit): ?><a class="workspace-button secondary" href="index.php?route=inventory">New item</a><?php endif; ?></div></form></section>
<?php if($edit && $edit['active']): ?><section class="workspace-card"><h2>Record stock movement</h2><p><strong><?php echo (int)$edit['quantity']; ?> <?php echo wh($edit['unit']); ?></strong> currently available</p><form method="post"><input type="hidden" name="action" value="move"><input type="hidden" name="csrf_token" value="<?php echo wh($workflowCsrf); ?>"><input type="hidden" name="id" value="<?php echo (int)$edit['id']; ?>"><input type="hidden" name="request_key" value="<?php echo wh(($_POST['action'] ?? '')==='move' ? ($_POST['request_key'] ?? '') : bin2hex(random_bytes(16))); ?>"><div class="workspace-fields"><label>Movement<select name="movement_type"><option value="receive">Receive stock</option><option value="issue">Issue stock</option><option value="return">Return to store</option><option value="write_off">Write off / damaged</option></select></label><label>Quantity<input type="number" name="quantity" min="1" max="1000000" step="1" required></label><label class="workspace-wide">Recipient / department (required for issues)<input name="recipient" maxlength="160"></label><label class="workspace-wide">Reason / delivery reference<textarea name="reason" maxlength="500" required></textarea></label></div><button class="workspace-button">Record movement</button></form>
<?php if((int)$edit['quantity']===0): ?><hr><form method="post" data-confirm="Archive this empty item? Its stock history will remain available."><input type="hidden" name="action" value="archive"><input type="hidden" name="csrf_token" value="<?php echo wh($workflowCsrf); ?>"><input type="hidden" name="id" value="<?php echo (int)$edit['id']; ?>"><label class="workspace-check"><input type="checkbox" name="confirm" value="yes" required> Confirm archiving this empty item</label><button class="workspace-button danger">Archive item</button></form><?php endif; ?></section><?php endif; ?></div>
<div><section class="workspace-card"><h2>Stock register</h2><label class="no-print">Find an item<input type="search" data-table-search="#inventory-table" placeholder="Name, code, category or location"></label><div class="workspace-table-wrap"><table class="workspace-table" id="inventory-table"><thead><tr><th>Item</th><th>Location</th><th>Available</th><th>Status</th><th></th></tr></thead><tbody><?php foreach($items as $i): ?><tr><td><strong><?php echo wh($i['name']); ?></strong><small><?php echo wh($i['sku'].' · '.$i['category']); ?></small></td><td><?php echo wh($i['location']); ?></td><td><?php echo (int)$i['quantity']; ?> <?php echo wh($i['unit']); ?><small>Reorder at <?php echo (int)$i['minimum_stock']; ?></small></td><td><span class="workspace-badge <?php echo !$i['active']?'muted':($i['quantity']<=$i['minimum_stock']?'warning':''); ?>"><?php echo !$i['active']?'Archived':($i['quantity']<=$i['minimum_stock']?'Low stock':'In stock'); ?></span></td><td><a href="index.php?route=inventory&amp;id=<?php echo (int)$i['id']; ?>">Manage</a></td></tr><?php endforeach; ?></tbody></table></div><?php if(!$items): ?><div class="workspace-empty">Your stock register is ready. Add an item, then record its opening stock as a receipt.</div><?php endif; ?></section>
<?php if($edit): ?><section class="workspace-card"><h2>Movement history · <?php echo wh($edit['name']); ?></h2><p class="workspace-muted">Latest 200 entries. Receipts change stock only; record related payments separately under Expenses.</p><div class="workspace-table-wrap"><table class="workspace-table"><thead><tr><th>When / recorded by</th><th>Movement</th><th>Quantity</th><th>Balance</th><th>Details</th></tr></thead><tbody><?php foreach($history as $m): ?><tr><td><?php echo wh($m['created_at']); ?><small><?php echo wh($m['created_by']); ?></small></td><td><?php echo wh(str_replace('_',' ',$m['movement_type'])); ?></td><td><?php echo (int)$m['quantity']; ?></td><td><?php echo (int)$m['balance_after']; ?></td><td><?php echo wh($m['reason']); ?><small><?php echo wh($m['recipient']); ?></small></td></tr><?php endforeach; ?></tbody></table></div><?php if(!$history): ?><p class="workspace-empty">No movements recorded yet.</p><?php endif; ?></section><?php endif; ?></div></div>
<?php require __DIR__ . '/workflow_footer.php'; ?>
