<?php
$noteService=new NoteService(database_pdo());$topics=$noteService->topics($_SESSION['active']);$note=null;$h=function($v){return htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');};
$error=$_SESSION['note_error'] ?? '';unset($_SESSION['note_error']);
$notice=$_SESSION['note_notice'] ?? '';unset($_SESSION['note_notice']);
try { if($portalRoute->param('item_ref')) $note=$noteService->get($portalRoute->param('item_ref'),$_SESSION['active'],'Instructor',true); }catch(Throwable $e){$error='This note is not available for editing.';}
$draft=$_SESSION['note_draft'] ?? array();unset($_SESSION['note_draft']);
if($draft && (int)($draft['id'] ?? 0)!==(int)($note['noteid'] ?? 0)) $draft=array();
$form=$draft ?: ($note ?: array());$type=$form['type'] ?? 'text';
?>
<div class="main_content_iner school-workspace"><div class="container-fluid p-0"><header class="workspace-heading"><div><p class="workspace-eyebrow">Teaching resources · <?php echo $h($noteService->activeTerm()); ?></p><h1><?php echo $note?'Edit lesson note':'Write a lesson note'; ?></h1><p>Give your class a clear explanation, useful examples and something to practise.</p></div><?php if($note): ?><a class="workspace-button secondary" href="../../app/router.php?pageid=note&amp;ref=<?php echo (int)$note['noteid']; ?>">View lesson</a><?php endif; ?></header>
<?php if($error): ?><div class="workspace-error" role="alert"><?php echo $h($error); ?></div><?php endif; ?><?php if($notice): ?><div class="workspace-notice" role="status"><?php echo $h($notice); ?></div><?php endif; ?>
<?php if(!$note || in_array($note['type'],array('text','online'),true)): ?>
<section class="workspace-card"><form method="post" action="../../app/note_action.php" id="lesson-note-form"><input type="hidden" name="csrf_token" value="<?php echo $h($_SESSION['portal_csrf']); ?>"><input type="hidden" name="id" value="<?php echo (int)($note['noteid'] ?? 0); ?>"><input type="hidden" name="version" value="<?php echo $h($draft['version'] ?? ($note?NoteService::version($note):'')); ?>">
<div class="workspace-fields"><label>Class, subject and topic<select name="topicid" required><option value="">Choose a scheme-of-work topic</option><?php foreach($topics as $topic): ?><option value="<?php echo (int)$topic['schmid']; ?>" <?php echo (int)($form['topicid'] ?? 0)===(int)$topic['schmid']?'selected':''; ?>><?php echo $h($topic['class_name'].' · '.$topic['sbjname'].' · '.$topic['week'].' · '.$topic['topic']); ?></option><?php endforeach; ?></select></label><label>Note format<select name="type" id="lesson-note-type"><option value="text" <?php echo $type==='text'?'selected':''; ?>>Written lesson</option><option value="online" <?php echo $type==='online'?'selected':''; ?>>Web resource</option></select></label></div>
<div id="lesson-written"><label for="lesson-content">Lesson content</label><p class="workspace-muted">Use headings, short paragraphs, examples and a short practice activity. Paste text or tables from your lesson plan.</p><textarea name="content" id="lesson-content" rows="18"><?php echo $h($type==='text'?($form['content'] ?? ''):''); ?></textarea><small id="lesson-word-count" aria-live="polite"></small></div>
<div id="lesson-web"><label>Learning resource URL<input type="url" name="weblink" id="lesson-weblink" maxlength="2000" placeholder="https://" value="<?php echo $h($form['weblink'] ?? ($type==='online'?($form['content'] ?? ''):'')); ?>"></label><p class="workspace-muted">Learners open external resources in a new tab. Only HTTP and HTTPS links are allowed.</p></div>
<div class="workspace-actions" style="margin-top:20px"><button class="workspace-button">Save lesson note</button><button type="button" class="workspace-button secondary" id="lesson-preview-button">Preview</button><span id="lesson-save-status" class="workspace-muted" role="status"></span></div><div class="note-preview note-content" id="lesson-preview" hidden></div></form></section>
<?php else: ?><section class="workspace-card"><p>This is an existing uploaded resource. You can read it as before, or add a new written lesson alongside it.</p><a class="workspace-button" href="../../app/router.php?pageid=resources&amp;item=add_note">Add written lesson</a></section><?php endif; ?>
<?php if($note): ?><section class="workspace-card"><details><summary>Remove this note from the library</summary><form method="post" action="../../app/note_action.php" data-confirm="Remove this lesson note from the class library?"><input type="hidden" name="csrf_token" value="<?php echo $h($_SESSION['portal_csrf']); ?>"><input type="hidden" name="action" value="remove"><input type="hidden" name="id" value="<?php echo (int)$note['noteid']; ?>"><input type="hidden" name="version" value="<?php echo $h(NoteService::version($note)); ?>"><label class="workspace-check"><input type="checkbox" name="confirm" value="yes" required> I confirm removal from the class library.</label><button class="workspace-button danger">Remove note</button></form></details></section><?php endif; ?></div></div>
