<?php
require __DIR__ . '/_common.php';
$review = $cbtAttemptService->learnerReview((int) $portalRoute->param('attempt_id'), $cbtActor);
$attempt = $review['attempt'];
?>
<div class="main_content_iner overly_inner cbt-portal">
    <div class="container-fluid p-0">
        <nav class="cbt-breadcrumb"><a href="../../app/router.php?pageid=cbt">My assessments</a><i class="fas fa-chevron-right"></i><span>Published result</span></nav>
        <header class="cbt-result-heading"><div><p class="cbt-kicker"><?php echo cbt_h($attempt['classname'] . ' · ' . $attempt['sbjname']); ?></p><h1><?php echo cbt_h($attempt['title']); ?></h1><p>Submitted <?php echo cbt_datetime($attempt['submitted_at']); ?> · <?php echo cbt_h($attempt['submission_ref']); ?></p></div><div class="cbt-result-score"><strong><?php echo cbt_h(number_format((float) $attempt['total_score'], 1)); ?><small>/ <?php echo cbt_h(number_format((float) $attempt['total_marks'], 1)); ?></small></strong><span><?php echo cbt_h(number_format((float) $attempt['percentage'], 1)); ?>% · Grade <?php echo cbt_h($attempt['grade']); ?></span></div></header>
        <?php if ($attempt['teacher_comment']): ?><div class="cbt-teacher-note"><i class="fas fa-comment-alt"></i><div><strong>Teacher’s note</strong><p><?php echo nl2br(cbt_h($attempt['teacher_comment'])); ?></p></div></div><?php endif; ?>
        <section class="cbt-board"><div class="cbt-board__title"><div><span class="cbt-section-number">S</span><h2>Submitted script</h2></div><p><?php echo count($review['questions']); ?> released responses</p></div><?php if (!$review['questions']): ?><div class="cbt-empty cbt-empty--small"><h3>Script review is not enabled</h3><p>Your published score and submission receipt remain available above.</p></div><?php else: ?><ol class="cbt-review-list"><?php foreach ($review['questions'] as $question): ?><li><header><span>Question <?php echo (int) $question['display_order']; ?></span><strong><?php echo cbt_h(number_format((float) $question['final_marks'], 1)); ?> / <?php echo cbt_h(number_format((float) $question['marks_available'], 1)); ?></strong></header><div class="cbt-script-question"><?php echo $question['prompt_snapshot']; ?></div><div class="cbt-review-grid"><div><small>Your answer</small><p><?php echo cbt_h(is_array($question['answer']) ? implode(', ', $question['answer']) : ($question['answer'] === null || $question['answer'] === '' ? 'Not answered' : $question['answer'])); ?></p></div><?php if ($question['correct_answer'] !== null): ?><div><small>Correct answer</small><p><?php echo cbt_h(is_array($question['correct_answer']) ? implode(', ', $question['correct_answer']) : $question['correct_answer']); ?></p></div><?php endif; ?></div><?php if ($question['marker_comment']): ?><p class="cbt-marker-comment"><strong>Feedback:</strong> <?php echo cbt_h($question['marker_comment']); ?></p><?php endif; ?><?php if ($question['explanation_snapshot']): ?><details><summary>Read the explanation</summary><p><?php echo nl2br(cbt_h($question['explanation_snapshot'])); ?></p></details><?php endif; ?></li><?php endforeach; ?></ol><?php endif; ?></section>
    </div>
</div>
